In [64]:
import numpy as np

In [2]:
import numpy as np

# deklarasikan variabel independent (x0(bias), x1, x2, x3)
x = np.array([[1, 0, 0, 0], 
              [1, 0, 0, 1], 
              [1, 0, 1, 0], 
              [1, 0, 1, 1], 
              [1, 1, 0, 0], 
              [1, 1, 0, 1], 
              [1, 1, 1, 0], 
              [1, 1, 1, 1]]) 

# deklarasikan variabel dependent (y)
y = np.array([[0, 0, 0, 1, 0, 1, 1, 1]])

# learning rate merupakan indikator yang mengatur tingkat pembelajaran mesin 
learningrate = 0.01

# berat awal yang nantinya akan diupdate
w_in = np.array([[-0.45, 0.23, -0.56, -0.7],
                [-0.65, 0.5, 0.83, -0.23]])

# berat dari hiden layer ke output (tidak akan diupdate)
w_hiden = np.array([[0.1054, 0.2364, 0.45]])

In [89]:
epoch = 1
while True:
    output = []
    error = []
    Z1 = []
    Z2 = []
    print('Epoch: ', epoch)
    for i in range(len(x)):
        
        z1 = sum(x[i]*w_in[0])
        Z1.append(z1)
        z2 = sum(x[i]*w_in[1])
        Z2.append(z2)
        if z1>= 0.5: fz1 = 1
        else: fz1 = 0
        if z2>= 0.5: fz2 = 1
        else: fz2 = 0
        
        O = z1*w_hiden[0][0] + z2*w_hiden[0][1] + w_hiden[0][2]
        if O >= 0.5: fO = 1
        else: fO = 0
        output.append(fO)
    
    for j in range(len(y[0])):
        error.append(y[0][j]-output[j])
    
    for e in range(len(error)):
        print('Iterasi ke', e)
        print(w_in)            
        if error[e] == 0:  continue
        if output[e] == 1:
            if np.abs(Z1[e]) < np.abs(Z2[e]):
                for s in range(4):
                    w_in[0][s] += learningrate*(y[0][e]-output[e])*x[e][s]
            else:
                for s in range(4):
                    w_in[1][s] += learningrate*(y[0][e]-output[e])*x[e][s]

        if output[e] == 0:
            for s in range(4):
                w_in[0][s] += learningrate*(y[0][e]-output[e])*x[e][s]
                w_in[1][s] += learningrate*(y[0][e]-output[e])*x[e][s]

    if np.sum(np.square(error))==0:
        break
    
    epoch += 1

Epoch:  1
Iterasi ke 0
[[-0.45  0.23 -0.56 -0.7 ]
 [-0.65  0.5   0.83 -0.23]]
Iterasi ke 1
[[-0.45  0.23 -0.56 -0.7 ]
 [-0.65  0.5   0.83 -0.23]]
Iterasi ke 2
[[-0.45  0.23 -0.56 -0.7 ]
 [-0.65  0.5   0.83 -0.23]]
Iterasi ke 3
[[-0.45  0.23 -0.56 -0.7 ]
 [-0.65  0.5   0.83 -0.23]]
Iterasi ke 4
[[-0.44  0.23 -0.55 -0.69]
 [-0.64  0.5   0.84 -0.22]]
Iterasi ke 5
[[-0.44  0.23 -0.55 -0.69]
 [-0.64  0.5   0.84 -0.22]]
Iterasi ke 6
[[-0.43  0.24 -0.55 -0.68]
 [-0.63  0.51  0.84 -0.21]]
Iterasi ke 7
[[-0.43  0.24 -0.55 -0.68]
 [-0.63  0.51  0.84 -0.21]]
Epoch:  2
Iterasi ke 0
[[-0.42  0.25 -0.54 -0.67]
 [-0.62  0.52  0.85 -0.2 ]]
Iterasi ke 1
[[-0.42  0.25 -0.54 -0.67]
 [-0.62  0.52  0.85 -0.2 ]]
Iterasi ke 2
[[-0.42  0.25 -0.54 -0.67]
 [-0.62  0.52  0.85 -0.2 ]]
Iterasi ke 3
[[-0.42  0.25 -0.54 -0.67]
 [-0.62  0.52  0.85 -0.2 ]]
Iterasi ke 4
[[-0.41  0.25 -0.53 -0.66]
 [-0.61  0.52  0.86 -0.19]]
Iterasi ke 5
[[-0.41  0.25 -0.53 -0.66]
 [-0.61  0.52  0.86 -0.19]]
Iterasi ke 6
[[-0.4   0.26 -